#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,… are generated by the following 
simple rule:
    
F(n) = {
        F(n-1) + F(n-2), n > 1
        1,               n = 1
        0,               n = 0
    }

Given: A positive integer n <= 25.

Return: The value of F(n).
"""

def fibonacci(n, memo):
    if n in memo:
        return memo[n]
    else:
        result = fibonacci(n-1, memo) + fibonacci(n-2, memo)
        memo[n] = result
        return result

if __name__ == '__main__':
    import fileinput

    with fileinput.input() as fin:
        N = int(fin.readline().strip())
    base_cases = {0:0, 1:1}

    print(fibonacci(N, base_cases))
